content: |-
  # Wayfinder Terraform Deployment for Azure

  ## Deployment

  1. Clone this repository
  2. Define tfvars file - use test.*.tftest.hcl files as a reference for example values
  3. Execute terrform (init, apply)

  ## Examples
  An example workflow (GitHub Workflow and Azure DevOps Pipeline examples) can be found in the 
  [examples](./examples) directory as well as an example tfvars file.

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:
  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject .`

  {{ .Inputs }}

  {{ .Outputs }}
